### PR TITLE
Added ilrepack

### PR DESCRIPTION
**Pull request by richardspence**
@TheFantasticLoki I had trouble getting ilmerge to work correctly and load up in unity.  I suspect a framework version issue, and so swapped to ilrepack for the same expected outcome.

### CODE REVIEW

**Comment by TheFantasticLoki** [comment]
Uhh, it should have been as simple as going into NuGet Package Manager and installing ILMerge. When you build it will do the merge after compiling everything else and it will throw errors saying you are missing certain files from the game directory like Newsoft.Json and such. But as long as you got it working ig that's fine.

**Comment by TheFantasticLoki** [comment]
BTW I am in the ONI Discord so if you need me for something like that in the future yo u can probably find me there

**Comment by richardspence** [comment]
Yeah it wasn't an issue with nuget, the merged binaries had BadFormatExceptions, and NativeDll exceptions at runtime, suggesting something wrong with the merged dlls.  Maybe the CLI arguments and the targeted framework was incorrect, but I swapped over to ilrepack regardless w/o investigating more time into ilmerge.

**Comment by TheFantasticLoki** [comment]
Actually that issue just means that the merge failed because you were missing some of the files it requires like Newsoft.json, ILMerge requires a few more of the game files and it will fail without them making a merged file that has 0 bytes giving the badformat exception. you just forgot to copy over the newly required files.

**Pull request merged**
